version: "3"

services:
  task_tracker:
    build:
      context: ../..
      dockerfile: build/Dockerfile
    container_name: task_tracker
    entrypoint: /start.fastapi.sh
    restart: on-failure
    ports:
      - "8080:8080"
    depends_on:
     - task_tracker_db
    expose:
      - 8080

  task_tracker_db:
    image: postgres:14
    container_name: task_tracker_db
    restart: on-failure
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Dankb2131193*
      - POSTGRES_DB=task_tracker

volumes:
      postgres_data:
